development:
  secret_key_base: f1fd8dd2ae76b04d4ddf3766d87c92458524857c1fdeb824fac75c82625597800798245e0a2a860d46f6bb8c6cdc4d30c7ec5c2b3316441f831beed302daab56
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: aefbbdc93b2d54fbddbfc30b647d975ba4ae37b150690aab2c6ef7783f3d60c1e9ee27ab498672e04c23f49f84a13e0210fc4ffe7b0d4a590af39dc2737800b6
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
