user:
  name:
    max_length: 50
  email:
    max_length: 255
  phone:
    max_length: 12
  date_of_birth:
    max_length: 10
  password:
    min_length: 6
product:
  name:
    max_length: 255
  limit: 4
  min_price: 0
  lastest_product: 4
  lastest_month: 1
